build_script:
  - cmd: "python tests.py"
clone_script:
  - cmd: "git clone https://github.com/ArneBachmann/awful .\\"
deploy: false
environment:
  PYTHONDONTWRITEBYTECODE: true
  matrix:
    - PYTHON_VERSION: 3.4
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.4
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.4
      platform: x86
      image: ubuntu1804
    - PYTHON_VERSION: 3.4
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.4
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.4
      platform: x64
      image: ubuntu1804
    - PYTHON_VERSION: 3.5
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.5
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.5
      platform: x86
      image: ubuntu1804
    - PYTHON_VERSION: 3.5
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.5
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.5
      platform: x64
      image: ubuntu1804
    - PYTHON_VERSION: 3.6
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.6
      platform: x86
      image: ubuntu1804
    - PYTHON_VERSION: 3.6
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.6
      platform: x64
      image: ubuntu1804
    - PYTHON_VERSION: 3.3
      platform: x86
      NOMYPY: true
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.3
      platform: x86
      NOMYPY: true
      image: ubuntu
    - PYTHON_VERSION: 3.3
      platform: x86
      NOMYPY: true
      image: ubuntu1804
    - PYTHON_VERSION: 3.3
      platform: x64
      NOMYPY: true
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.3
      platform: x64
      NOMYPY: true
      image: ubuntu
    - PYTHON_VERSION: 3.3
      platform: x64
      NOMYPY: true
      image: ubuntu1804
    - PYTHON_VERSION: 3.6
      platform: x64
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x64
      image: ubuntu
    - PYTHON_VERSION: 3.6
      platform: x64
      image: ubuntu1804
    - PYTHON_VERSION: 3.6
      platform: x86
      image: Visual Studio 2013
    - PYTHON_VERSION: 3.6
      platform: x86
      image: ubuntu
    - PYTHON_VERSION: 3.6
      platform: x86
      image: ubuntu1804
init:
  - "set PY_VER=%PYTHON_VERSION:.=%"
  - "set PYTHON=C:\\PYTHON%PY_VER%"
  - "if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
skip_branch_with_pr: true
version: "{build}.{branch}"
